spring.application.name=customer-service-mercury-app

# H2 Database
spring.datasource.url=jdbc:h2:mem:customerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
rest.server.port=8100
server.port=8085

log.format=text
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/public/

web.component.scan=com.deviceshop.customer

snake.case.serialization=true
show.application.properties=server.port,spring.application.name

rest.automation=true
yaml.rest.automation=classpath:/rest.yaml
yaml.flow.automation=classpath:/flows.yaml
