spring.application.name=customer-service-mercury-app
server.port=8100

log.format=text
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/public/

web.component.scan=com.deviceshop.customer

snake.case.serialization=true
show.application.properties=server.port,spring.application.name

rest.automation=true
yaml.rest.automation=classpath:/rest.yaml
yaml.flow.automation=classpath:/flows.yaml